#!/usr/bin/env bash

#
# Test script for AP1
#
# Platform: Linux, Mac
# Author:   George Karlos
#

rm -f expressions.in.txt expressions.out.txt && python util/generate_expressions.py > expressions.in.txt
cat expressions.in.txt | while read -r line;
do 
  printf "$line = "; 
  awk "BEGIN {print $line}" | tee -a expressions.out.txt; 
done
echo
echo 'Your answers:'
echo
cat expressions.in.txt | java -jar build/libs/AP1-1.0.jar
